# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProficiencyExecercise-Wipro' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProficiencyExecercise-Wipro
	pod 'Alamofire'
  pod 'SDWebImage'
  pod 'NVActivityIndicatorView'

  target 'ProficiencyExecercise-WiproTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProficiencyExecercise-WiproUITests' do
    # Pods for testing
  end

end
